{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-cr
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-crb
  labels:
    {{- include "kubernetes-dependecy-tracker.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "kubernetes-dependecy-tracker.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-cr
  apiGroup: rbac.authorization.k8s.io
{{- end }}
